import = [ "~/.config/alacritty/themes/themes/dracula.toml" ]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "none"
opacity = 0.9
startup_mode = "Windowed"
title = "Allapparai"
dynamic_title = false
# gtk_theme_variant = "dark"

  [window.dimensions]
  columns = 80
  lines = 24

  [window.padding]
  x = 2
  y = 2

  [window.class]
  instance = "Alacritty"
  general = "Alacritty"

[scrolling]
history = 10_000
multiplier = 3

[font]
size = 15

  [font.normal]
  family = "JetBrains Mono NL"
  style = "Bold"

  [font.italic]
  family = "JetBrains Mono NL"
  style = "Italic"

  [font.bold_italic]
  family = "JetBrains Mono NL"
  style = "Bold Italic"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[shell]
program = "/bin/zsh"
args = [ "--login" ]
